CREATE TABLE Customers (
    CustomerID NUMBER PRIMARY KEY,
    Name VARCHAR2(100),
    DOB DATE,
    Balance NUMBER,
    LastModified DATE
);
CREATE TABLE Accounts (
    AccountID NUMBER PRIMARY KEY,
    CustomerID NUMBER,
    AccountType VARCHAR2(20),
    Balance NUMBER,
    LastModified DATE,
    FOREIGN KEY (CustomerID)
    REFERENCES Customers(CustomerID)
);
CREATE TABLE Employees (
    EmployeeID NUMBER PRIMARY KEY,
    Name VARCHAR2(100),
    Position VARCHAR2(50),
    Salary NUMBER,
    Department VARCHAR2(50),
    HireDate DATE
);
CREATE TABLE ErrorLog (
    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ErrorMessage VARCHAR2(200),
    LogDate DATE
);
INSERT INTO Customers
VALUES (
    1,
    'John Doe',
    TO_DATE('1985-05-15','YYYY-MM-DD'),
    1000,
    SYSDATE
);

INSERT INTO Customers
VALUES (
    2,
    'Jane Smith',
    TO_DATE('1990-07-20','YYYY-MM-DD'),
    1500,
    SYSDATE
);

COMMIT;
INSERT INTO Accounts
VALUES (
    1,
    1,
    'Savings',
    1000,
    SYSDATE
);

INSERT INTO Accounts
VALUES (
    2,
    2,
    'Checking',
    1500,
    SYSDATE
);

COMMIT;
INSERT INTO Employees
VALUES (
    1,
    'Alice Johnson',
    'Manager',
    70000,
    'HR',
    TO_DATE('2015-06-15','YYYY-MM-DD')
);

INSERT INTO Employees
VALUES (
    2,
    'Bob Brown',
    'Developer',
    60000,
    'IT',
    TO_DATE('2017-03-20','YYYY-MM-DD')
);

COMMIT;
CREATE OR REPLACE PROCEDURE SafeTransferFunds(
    p_FromAccountID IN NUMBER,
    p_ToAccountID   IN NUMBER,
    p_Amount        IN NUMBER
)
IS
    v_Balance NUMBER;
BEGIN

    -- Get source account balance
    SELECT Balance
    INTO v_Balance
    FROM Accounts
    WHERE AccountID = p_FromAccountID;

    -- Check sufficient funds
    IF v_Balance < p_Amount THEN

        INSERT INTO ErrorLog(
            ErrorMessage,
            LogDate
        )
        VALUES (
            'Insufficient Funds',
            SYSDATE
        );

        RAISE_APPLICATION_ERROR(
            -20001,
            'Insufficient Funds'
        );

    END IF;

    -- Deduct amount from source account
    UPDATE Accounts
    SET Balance = Balance - p_Amount
    WHERE AccountID = p_FromAccountID;

    -- Add amount to destination account
    UPDATE Accounts
    SET Balance = Balance + p_Amount
    WHERE AccountID = p_ToAccountID;

    COMMIT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        INSERT INTO ErrorLog(
            ErrorMessage,
            LogDate
        )
        VALUES (
            'Account Not Found',
            SYSDATE
        );

        ROLLBACK;

    WHEN OTHERS THEN
        INSERT INTO ErrorLog(
            ErrorMessage,
            LogDate
        )
        VALUES (
            'Unexpected Error',
            SYSDATE
        );

        ROLLBACK;
END;
/
SHOW ERRORS PROCEDURE SafeTransferFunds;
SELECT line, position, text
FROM user_errors
WHERE name = 'SAFETRANSFERFUNDS'
ORDER BY sequence;
BEGIN
    SafeTransferFunds(1,2,500);
END;
/
SELECT * FROM Accounts;
CREATE OR REPLACE PROCEDURE UpdateSalary(
    p_EmployeeID IN NUMBER,
    p_Percentage IN NUMBER
)
IS
BEGIN

    UPDATE Employees
    SET Salary =
        Salary + (Salary * p_Percentage / 100)
    WHERE EmployeeID = p_EmployeeID;

    IF SQL%ROWCOUNT = 0 THEN

        INSERT INTO ErrorLog(ErrorMessage, LogDate)
        VALUES (
            'Employee ID Not Found',
            SYSDATE
        );

        RAISE_APPLICATION_ERROR(
            -20002,
            'Employee ID Not Found'
        );

    END IF;

    COMMIT;

END;
/
BEGIN
    UpdateSalary(1,10);
END;
/
SELECT * FROM Employees;
CREATE OR REPLACE PROCEDURE AddNewCustomer(
    p_CustomerID IN NUMBER,
    p_Name       IN VARCHAR2,
    p_DOB        IN DATE,
    p_Balance    IN NUMBER
)
IS
BEGIN

    INSERT INTO Customers
    VALUES (
        p_CustomerID,
        p_Name,
        p_DOB,
        p_Balance,
        SYSDATE
    );

    COMMIT;

EXCEPTION

    WHEN DUP_VAL_ON_INDEX THEN

        INSERT INTO ErrorLog(
            ErrorMessage,
            LogDate
        )
        VALUES (
            'Customer ID Already Exists',
            SYSDATE
        );

        COMMIT;

END;
/
BEGIN
    AddNewCustomer(
        3,
        'David Wilson',
        TO_DATE(
            '1995-08-10',
            'YYYY-MM-DD'
        ),
        2000
    );
END;
/
SELECT * FROM Customers;

SELECT * FROM Accounts;

SELECT * FROM Employees;

SELECT * FROM ErrorLog;