ALTER USER BankDB_Exercise1
QUOTA UNLIMITED ON USERS;
COMMIT;
CREATE USER BankDB_Exercise2
IDENTIFIED BY Bank123;
GRANT CONNECT, RESOURCE TO BankDB_Exercise2;

ALTER USER BankDB_Exercise2
QUOTA UNLIMITED ON USERS;
SELECT username
FROM dba_users
WHERE username = 'BANKDB_EXERCISE2';
CREATE USER BankDB_Exercise2
IDENTIFIED BY 1331;
ALTER USER BANKDB_EXERCISE2
IDENTIFIED BY 1331;
ALTER USER BANKDB_EXERCISE2
QUOTA UNLIMITED ON USERS;

CREATE USER BankDB_Exercise3
IDENTIFIED BY 1331;

GRANT CONNECT, RESOURCE TO BankDB_Exercise3;

ALTER USER BankDB_Exercise3
QUOTA UNLIMITED ON USERS;

CREATE USER BankDB_Exercise4
IDENTIFIED BY 1331;

GRANT CONNECT, RESOURCE TO BankDB_Exercise4;

ALTER USER BankDB_Exercise4
QUOTA UNLIMITED ON USERS;

CREATE USER BankDB_Exercise5
IDENTIFIED BY 1331;

GRANT CONNECT, RESOURCE TO BankDB_Exercise5;

ALTER USER BankDB_Exercise5
QUOTA UNLIMITED ON USERS;

CREATE USER BankDB_Exercise6
IDENTIFIED BY 1331;

GRANT CONNECT, RESOURCE TO BankDB_Exercise6;

ALTER USER BankDB_Exercise6
QUOTA UNLIMITED ON USERS;

CREATE USER BankDB_Exercise7
IDENTIFIED BY 1331;

GRANT CONNECT, RESOURCE TO BankDB_Exercise7;

ALTER USER BankDB_Exercise7
QUOTA UNLIMITED ON USERS;