CREATE USER BankDB_Exercise1
IDENTIFIED BY Bank123;
GRANT CONNECT, RESOURCE TO BankDB_Exercise1;

GRANT CREATE SESSION TO BankDB_Exercise1;
GRANT CREATE TABLE TO BankDB_Exercise1;
GRANT CREATE PROCEDURE TO BankDB_Exercise1;
GRANT CREATE TRIGGER TO BankDB_Exercise1;